name: TwipR
main: com.gmail.lilllung09.twipr.TwipR
version: 3.1.0
author : lilllung09
description : lilllung09 first plugin
commands :
  twipr :
    description : main commands
libraries:
  - com.neovisionaries:nv-websocket-client:2.14